decisiontree:
  max_depth:
    min: 1
    max: 20
  min_samples_split:
    min: 2
    max: 20
  min_samples_leaf:
    min: 1
    max: 10
  max_features:
    min: 0.5
    max: 1.0  # 전체 피처의 비율, 1.0은 모든 피처 사용 의미

randomforest:
  n_estimators:
    min: 100
    max: 500
  max_depth:
    min: 1
    max: 20
  min_samples_split:
    min: 2
    max: 20
  min_samples_leaf:
    min: 1
    max: 10
  max_features:
    min: 0.5
    max: 1.0  # 전체 피처의 비율, 1.0은 모든 피처 사용 의미
  bootstrap:
    values: [true, false]

lightgbm:
  num_leaves:
    min: 20
    max: 50
  learning_rate:
    min: 0.01
    max: 0.3
  n_estimators:
    min: 500
    max: 2000
  max_depth:
    min: -1  # -1은 제한 없음
    max: 20
  subsample:
    min: 0.5
    max: 1.0
  colsample_bytree:
    min: 0.5
    max: 1.0
  reg_alpha:
    min: 0.0
    max: 1.0
  reg_lambda:
    min: 0.0
    max: 1.0

xgboost:
  max_depth:
    min: 3
    max: 10
  learning_rate:
    min: 0.01
    max: 0.3
  n_estimators:
    min: 500
    max: 2000
  colsample_bytree:
    min: 0.5
    max: 1.0
  subsample:
    min: 0.5
    max: 1.0
  reg_alpha:
    min: 0.0
    max: 1.0
  reg_lambda:
    min: 0.0
    max: 1.0
  min_child_weight:
    min: 1
    max: 10
  gamma:
    min: 0.0
    max: 0.5

transformer:
  dim: 22
  num_heads: 2
  hidden_dim: 64
  num_layers: 4
  learning_rate: 0.001
  epochs: 10
  threshold: 3
  window_minutes: 10
  stride_minutes : 5
  length: 49
  batch_size: 32
